apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  labels:
    app: myapp
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      tier: backend
  template:
    metadata:
      labels:
        app: myapp
        tier: backend
    spec:
      dnsPolicy: ClusterFirst
      dnsConfig:
        nameservers:
          - 8.8.8.8 # Google's public DNS (optional)
      containers:
      - name: server
        image: shouryap1/backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: NODE_ENV
          value: "development"
        - name: MONGO_URI
          value: "mongodb+srv://ritikgupta1424:EUptZ6OUOqSwGKec@cluster0.vqbikv5.mongodb.net/YOUR_DB_NAME?retryWrites=true&w=majority"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: myapp
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
      tier: frontend
  template:
    metadata:
      labels:
        app: myapp
        tier: frontend
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: client
        image: shouryap1/frontend:latest
        ports:
        - containerPort: 5173
        env:
        - name: NODE_ENV
          value: "development"
        - name: BACKEND_URL
          value: "http://server-service:8000" # Use internal DNS for backend service
        readinessProbe:
          httpGet:
            path: /api/health  # Endpoint to check backend health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
          failureThreshold: 3
