version: '3.7'

services:
  server:
    image: shouryap1/backend:latest
    container_name: myapp-node-server
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=development
      - MONGO_URI=mongodb+srv://ritikgupta1424:WRdnbS610yMdL6lT@cluster0.vqbikv5.mongodb.net/
    networks:
      - app-network
    depends_on:
      - client
    volumes:
      - /app/node_modules
    dns:
      - 8.8.8.8  # Use Google's public DNS to ensure proper DNS resolution

  client:
    image: shouryap1/frontend:latest
    container_name: myapp-react-client
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    networks:
      - app-network
    volumes:
      - /app/node_modules

networks:
  app-network:
    driver: bridge

volumes:
  node_modules:
