apiVersion: v1
kind: Service
metadata:
  name: server-service
  labels:
    app: myapp
spec:
  type: NodePort
  selector:
    app: myapp
    tier: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30000  # Exposed port on the node for external access (if needed)

---
apiVersion: v1
kind: Service
metadata:
  name: client-service
  labels:
    app: myapp
spec:
  type: NodePort
  selector:
    app: myapp
    tier: frontend
  ports:
  - protocol: TCP
    port: 5173
    targetPort: 5173
    nodePort: 30001  # Exposed port on the node for external access (if needed)
